<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net48;net7.0-windows</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<OutputType>Library</OutputType>

		<UseWindowsForms>true</UseWindowsForms>
		
		<AssemblyName>Nuclei3</AssemblyName>
		<RootNamespace>Nuclei3</RootNamespace>

		<TargetExt>.gha</TargetExt>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AssemblyIcon>Nuclei.ico</AssemblyIcon>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Grasshopper" Version="8.0.*" />
		<PackageReference Include="RhinoCommon" Version="8.0.*" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx" Generator="ResXFileCodeGenerator" LastGenOutput="Resources.Designer.cs" />
	</ItemGroup>

	<PropertyGroup Condition="$(Configuration) == 'Debug'">
		<StartAction>Program</StartAction>
		<StartProgram>C:\Program Files\Rhino 8\System\Rhino.exe</StartProgram>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="$(TargetPath)" DestinationFiles="$(AppData)\Grasshopper\Libraries\$(TargetName).gha" />
	</Target>
</Project>