<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="RhinoCommon">
      <HintPath Condition="'$(TargetFramework)' != 'net48'">C:\Program Files\Rhino 9 WIP\System\netcore\RhinoCommon.dll</HintPath>
      <HintPath Condition="'$(TargetFramework)' == 'net48'">C:\Program Files\Rhino 9 WIP\System\RhinoCommon.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Grasshopper">
      <HintPath>C:\Program Files\Rhino 9 WIP\Plug-ins\Grasshopper\Grasshopper.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GH_IO">
      <HintPath>C:\Program Files\Rhino 9 WIP\Plug-ins\Grasshopper\GH_IO.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
