<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>Nuclei.DefinitionValidationHost.NetFx</AssemblyName>
    <RootNamespace>Nuclei.DefinitionValidationHost.NetFx</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="NetFxBootstrap.cs" />
    <Compile Include="NetFxHost.cs" />
    <Reference Include="RhinoCommon">
      <HintPath>C:\Program Files\Rhino 9 WIP\System\RhinoCommon.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Grasshopper">
      <HintPath>C:\Program Files\Rhino 9 WIP\Plug-ins\Grasshopper\Grasshopper.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GH_IO">
      <HintPath>C:\Program Files\Rhino 9 WIP\Plug-ins\Grasshopper\GH_IO.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>C:\Program Files\Rhino 9 WIP\System\Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
